/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.saladejogo.ui;

import client.socket.Conexao;
import client.socket.Solicitacao;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author vntwafi
 */
public class TelaAguardandoVencedor extends javax.swing.JPanel {

    private final JFrame frameLayout;
    private ObjectOutputStream transmissor;
    private ObjectInputStream receptor;
    private final String nomePartida;
    private final Socket conexao;
    /**
     * Creates new form TelaAguardando
     * @param framelayout
     * @param nome
     */
    public TelaAguardandoVencedor(JFrame framelayout, String nome) {
        initComponents();
        this.frameLayout = framelayout;
        this.frameLayout.add(this);
        this.frameLayout.addWindowListener(exitListener);
        this.frameLayout.pack();
        this.frameLayout.setLocationRelativeTo(null); 
        this.frameLayout.setResizable(false);
        this.frameLayout.setVisible(true);
        this.nomePartida = nome;
        this.conexao = Conexao.getSocket();
        atualizarVencedor(this.nomePartida);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNumJogadores = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 23, 23));
        jLabel1.setText("Aguarde o moderador iniciar a partida");

        lblNumJogadores.setText("Vencedor:");

        lblValor.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(lblNumJogadores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValor)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumJogadores)
                    .addComponent(lblValor))
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarVencedor(String nomePartida)
    {
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                boolean condicao = true;
                while(condicao)
                {
                    if(Conexao.getSocket() != null)
                    {
                        Solicitacao solicitacao = new Solicitacao("UWG", nomePartida);
                        Solicitacao retorno;
                        try 
                        {
                            transmissor = Conexao.getOutputStream();
                            receptor = Conexao.getInputStream();
                            transmissor.writeObject(solicitacao);
                            transmissor.flush(); //envio imediato
                            retorno = (Solicitacao) receptor.readObject();
                            System.out.println(retorno.toString());
                            if(retorno.getComando().toUpperCase().equals("WIN"))
                            {
                                condicao = false;
                                lblValor.setText(retorno.getComplemento1());
                                
                            }
                        } 
                        catch (IOException | ClassNotFoundException ex) 
                        {
                            Logger.getLogger(TelaAguardandoVencedor.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }                    
                }

            }
        }, 2000);
    }
    WindowListener exitListener = new WindowAdapter() {

        @Override
        public void windowClosing(WindowEvent e) {
            int confirm = JOptionPane.showOptionDialog(
                 null, "Tem certeza que deseja fechar o jogo?", 
                 "Exit Confirmation", JOptionPane.YES_NO_OPTION, 
                 JOptionPane.QUESTION_MESSAGE, null, null, null);
            if (confirm == 0) 
            {
                Solicitacao retorno;
                try 
                {
                    transmissor = Conexao.getOutputStream();
                    receptor = Conexao.getInputStream();
                    transmissor.writeObject(new Solicitacao("SAI"));
                    transmissor.flush(); //envio imediato
                    retorno = (Solicitacao) receptor.readObject();
                    System.out.println(retorno.toString());
                    if(retorno.getComando().toUpperCase().equals("SUC"))
                    {
                        System.exit(0);
                    }
                }
                catch (IOException | ClassNotFoundException ex) 
                {
                    Logger.getLogger(TelaAguardando.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNumJogadores;
    private javax.swing.JLabel lblValor;
    // End of variables declaration//GEN-END:variables
}
