/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.saladejogo.ui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import client.socket.Solicitacao;
/**
 *
 * @author vntwafi
 */
public class TelaPartida extends javax.swing.JPanel {

    ObjectOutputStream transmissor;
    ObjectInputStream receptor;
    Socket conexao;
    JFrame frameLayout;
    /**
     * Creates new form TelaPartida
     * @param framelayout
     */
    public TelaPartida(JFrame framelayout)
    {
        initComponents();
        this.frameLayout = framelayout;
        this.frameLayout.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.frameLayout.add(this);
        Dimension d = new Dimension(900, 540);
        this.frameLayout.setSize(d);
        this.frameLayout.setLocationRelativeTo(null);
        this.frameLayout.setResizable(false);
        this.frameLayout.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnParar = new javax.swing.JButton();
        btnMaisCartas = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblValorMesa = new javax.swing.JLabel();
        lblAposta = new javax.swing.JLabel();
        lblSeusPontos = new javax.swing.JLabel();
        lblPontos = new javax.swing.JLabel();
        lblBaseCartas = new javax.swing.JLabel();
        carta1 = new javax.swing.JLabel();
        carta2 = new javax.swing.JLabel();
        carta4 = new javax.swing.JLabel();
        carta5 = new javax.swing.JLabel();
        carta3 = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setLayout(null);

        btnParar.setBackground(new java.awt.Color(255, 255, 255));
        btnParar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnParar.setForeground(new java.awt.Color(255, 255, 255));
        btnParar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/saladejogo/ui/btnParar.png"))); // NOI18N
        btnParar.setText("PARAR");
        btnParar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnParar.setIconTextGap(6);
        btnParar.setPreferredSize(new java.awt.Dimension(100, 50));
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });
        add(btnParar);
        btnParar.setBounds(480, 420, 123, 40);

        btnMaisCartas.setBackground(new java.awt.Color(255, 255, 255));
        btnMaisCartas.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnMaisCartas.setForeground(new java.awt.Color(255, 255, 255));
        btnMaisCartas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/saladejogo/ui/btnMais.png"))); // NOI18N
        btnMaisCartas.setText("MAIS CARTAS");
        btnMaisCartas.setToolTipText("");
        btnMaisCartas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMaisCartas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMaisCartas.setIconTextGap(6);
        btnMaisCartas.setRolloverEnabled(true);
        btnMaisCartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisCartasActionPerformed(evt);
            }
        });
        add(btnMaisCartas);
        btnMaisCartas.setBounds(280, 420, 123, 40);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/saladejogo/ui/logo.png"))); // NOI18N
        add(lblLogo);
        lblLogo.setBounds(50, 30, 383, 81);

        lblStatus.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblStatus.setText("Status do Jogo:");
        add(lblStatus);
        lblStatus.setBounds(50, 120, 140, 30);

        lblValorMesa.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblValorMesa.setForeground(new java.awt.Color(255, 0, 0));
        lblValorMesa.setText("$ 15K");
        add(lblValorMesa);
        lblValorMesa.setBounds(180, 152, 45, 16);

        lblAposta.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblAposta.setText("Aposta MEGA:");
        add(lblAposta);
        lblAposta.setBounds(50, 150, 140, 20);

        lblSeusPontos.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblSeusPontos.setText("SEUS PONTOS:");
        lblSeusPontos.setToolTipText("");
        add(lblSeusPontos);
        lblSeusPontos.setBounds(340, 370, 170, 30);

        lblPontos.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblPontos.setText("4");
        add(lblPontos);
        lblPontos.setBounds(520, 370, 170, 30);

        lblBaseCartas.setBackground(new java.awt.Color(153, 153, 153));
        lblBaseCartas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/saladejogo/ui/efeitoDeck.png"))); // NOI18N
        add(lblBaseCartas);
        lblBaseCartas.setBounds(150, 290, 550, 60);

        carta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/saladejogo/ui/copas-10.jpg"))); // NOI18N
        carta1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        carta1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(carta1);
        carta1.setBounds(150, 180, 110, 160);

        carta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/saladejogo/ui/espadas-9.jpg"))); // NOI18N
        carta2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        carta2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(carta2);
        carta2.setBounds(590, 180, 110, 160);

        carta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/saladejogo/ui/espadas-9.jpg"))); // NOI18N
        carta4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        carta4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(carta4);
        carta4.setBounds(370, 180, 110, 160);

        carta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/saladejogo/ui/espadas-9.jpg"))); // NOI18N
        carta5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        carta5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(carta5);
        carta5.setBounds(480, 180, 110, 160);

        carta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/saladejogo/ui/copas-10.jpg"))); // NOI18N
        carta3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        carta3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(carta3);
        carta3.setBounds(260, 180, 110, 160);

        lblFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/client/saladejogo/ui/fundoTestura.png"))); // NOI18N
        lblFundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblFundo);
        lblFundo.setBounds(0, 0, 900, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        Solicitacao parada = new Solicitacao("EOC");
        Solicitacao retorno;
        try
        {
            this.transmissor.writeObject(parada);
            this.transmissor.flush();
            retorno = (Solicitacao) this.receptor.readObject();
            if(retorno.getComando().toUpperCase().equals("SUC"))
            {

            }
        }
        catch (IOException | ClassNotFoundException ex)
        {
            Logger.getLogger(TelaPartida.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPararActionPerformed

    private void btnMaisCartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisCartasActionPerformed
        Solicitacao pedido = new Solicitacao("COM");
        Solicitacao retorno;
        Graphics g = null;
        
        AffineTransform at = AffineTransform.getTranslateInstance(100, 100);
        at.rotate(Math.toRadians(45));
        BufferedImage carta3 = loadImage("/saladejogo/ui/espadas-9.jpg");
//        try
//        {
//            this.transmissor.writeObject(pedido);
//            this.transmissor.flush();
//            retorno = (Solicitacao) this.receptor.readObject();
//            System.out.println(retorno.toString());
//            if(retorno.getComando().toUpperCase().equals("SUC"))
//            {
//
//            }
//        }
//        catch (IOException | ClassNotFoundException ex)
//        {
//            Logger.getLogger(TelaPartida.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnMaisCartasActionPerformed
    BufferedImage loadImage(String fileName) {
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(fileName));
            
        } catch (IOException e) {
        }
        
        return img;
    }
    
    	static class RotateLabel extends JLabel {
		private static final long serialVersionUID = 1L;
		private int angle = 0;

		public RotateLabel( String text, int x, int y ) {
			super( text );
			setBorder( new javax.swing.border.CompoundBorder( new javax.swing.border.LineBorder( Color.red, 1), getBorder() ) );
			int width = getPreferredSize().width;
			int height = getPreferredSize().height;
			setBounds( x, y, width, height );
		}

		@Override
		public void paintComponent( Graphics g ) {
			Graphics2D gx = (Graphics2D) g;
			gx.rotate(0.2, getX() + getWidth() / 2, getY() + getHeight() / 2);
			super.paintComponent(g);
		}

		public void setRotation( int angle ) { this.angle = angle; }
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMaisCartas;
    private javax.swing.JButton btnParar;
    private javax.swing.JLabel carta1;
    private javax.swing.JLabel carta2;
    private javax.swing.JLabel carta3;
    private javax.swing.JLabel carta4;
    private javax.swing.JLabel carta5;
    private javax.swing.JLabel lblAposta;
    private javax.swing.JLabel lblBaseCartas;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPontos;
    private javax.swing.JLabel lblSeusPontos;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblValorMesa;
    // End of variables declaration//GEN-END:variables
}
