/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saladejogo.ui;

import client.socket.Conexao;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import socket.Solicitacao;

/**
 *
 * @author Calebe
 */
public class PartidaUI extends javax.swing.JFrame {

    ObjectOutputStream transmissor;
    ObjectInputStream receptor;
    Socket conexao;
    /**
     * Creates new form Partida
     */
    public PartidaUI() 
    {
        initComponents();
        this.transmissor = Conexao.getOutputStream();
        this.receptor = Conexao.getInputStream();
        this.conexao = Conexao.getSocket();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnParar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnMaisCartas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblValorMesa = new javax.swing.JLabel();
        lblPontos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saladejogo/ui/field2.jpeg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        btnParar.setBackground(new java.awt.Color(255, 255, 255));
        btnParar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnParar.setForeground(new java.awt.Color(255, 255, 255));
        btnParar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saladejogo/ui/btnParar.png"))); // NOI18N
        btnParar.setText("PARAR");
        btnParar.setBounds(new java.awt.Rectangle(480, 420, 123, 40));
        btnParar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnParar.setIconTextGap(6);
        btnParar.setPreferredSize(new java.awt.Dimension(100, 50));
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });
        getContentPane().add(btnParar);
        btnParar.setBounds(480, 420, 123, 40);

        btnSair.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saladejogo/ui/btnParar.png"))); // NOI18N
        btnSair.setText("x");
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(860, 10, 25, 20);

        btnMaisCartas.setBackground(new java.awt.Color(255, 255, 255));
        btnMaisCartas.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnMaisCartas.setForeground(new java.awt.Color(255, 255, 255));
        btnMaisCartas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saladejogo/ui/btnMais.png"))); // NOI18N
        btnMaisCartas.setText("MAIS CARTAS");
        btnMaisCartas.setToolTipText("");
        btnMaisCartas.setBounds(new java.awt.Rectangle(280, 420, 123, 40));
        btnMaisCartas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMaisCartas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMaisCartas.setIconTextGap(6);
        btnMaisCartas.setRolloverEnabled(true);
        btnMaisCartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisCartasActionPerformed(evt);
            }
        });
        getContentPane().add(btnMaisCartas);
        btnMaisCartas.setBounds(280, 420, 123, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saladejogo/ui/efeitoDeck.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 290, 510, 60);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Aposta MEGA:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 150, 140, 20);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Status do Jogo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 120, 140, 30);

        lblValorMesa.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblValorMesa.setForeground(new java.awt.Color(255, 0, 0));
        lblValorMesa.setText("$ 15K");
        getContentPane().add(lblValorMesa);
        lblValorMesa.setBounds(180, 152, 45, 16);

        lblPontos.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblPontos.setText("4");
        getContentPane().add(lblPontos);
        lblPontos.setBounds(520, 370, 170, 30);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("SEUS PONTOS:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 370, 170, 30);

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 565, 34);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saladejogo/ui/logo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 30, 383, 81);

        lblFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saladejogo/ui/fundoTestura.png"))); // NOI18N
        lblFundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 900, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaisCartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisCartasActionPerformed
        Solicitacao pedido = new Solicitacao("COM");
        Solicitacao retorno;
        try 
        {
            this.transmissor.writeObject(pedido);
            this.transmissor.flush();
            retorno = (Solicitacao) this.receptor.readObject();
            System.out.println(retorno.toString());
            if(retorno.getComando().toUpperCase().equals("SUC"))
            {
                
            }
        } 
        catch (IOException | ClassNotFoundException ex) 
        {
            Logger.getLogger(PartidaUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnMaisCartasActionPerformed

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        Solicitacao parada = new Solicitacao("EOC");
        Solicitacao retorno;
        try 
        {
            this.transmissor.writeObject(parada);
            this.transmissor.flush();
            retorno = (Solicitacao) this.receptor.readObject();
            if(retorno.getComando().toUpperCase().equals("SUC"))
            {
                
            }            
        } 
        catch (IOException | ClassNotFoundException ex) 
        {
            Logger.getLogger(PartidaUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnPararActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Solicitacao sair = new Solicitacao("SAI");
        Solicitacao retorno;
        try 
        {
            this.transmissor.writeObject(sair);
            this.transmissor.flush();
            retorno = (Solicitacao) this.receptor.readObject();
            if(retorno.getComando().toUpperCase().equals("SUC"))
            {
                Conexao.closeConnection();
            }            
        } 
        catch (IOException | ClassNotFoundException ex) 
        {
            Logger.getLogger(PartidaUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartidaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartidaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartidaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartidaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartidaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMaisCartas;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblPontos;
    private javax.swing.JLabel lblValorMesa;
    // End of variables declaration//GEN-END:variables
}
