/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saladejogo.ui;

import java.awt.Dimension;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import socket.Solicitacao;
/**
 *
 * @author vntwafi
 */
public class TelaPartida extends javax.swing.JPanel {

    ObjectOutputStream transmissor;
    ObjectInputStream receptor;
    Socket conexao;
    JFrame frameLayout;
    /**
     * Creates new form TelaPartida
     * @param framelayout
     */
    public TelaPartida(JFrame framelayout)
    {
        initComponents();
        this.frameLayout = framelayout;
        this.frameLayout.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.frameLayout.add(this);
        Dimension d = new Dimension(900, 540);
        this.frameLayout.setSize(d);
        this.frameLayout.setLocationRelativeTo(null);
        this.frameLayout.setResizable(false);
        this.frameLayout.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnParar = new javax.swing.JButton();
        btnMaisCartas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblValorMesa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPontos = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setLayout(null);

        btnParar.setBackground(new java.awt.Color(255, 255, 255));
        btnParar.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnParar.setForeground(new java.awt.Color(255, 255, 255));
        btnParar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saladejogo/ui/btnParar.png"))); // NOI18N
        btnParar.setText("PARAR");
        btnParar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnParar.setIconTextGap(6);
        btnParar.setPreferredSize(new java.awt.Dimension(100, 50));
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });
        add(btnParar);
        btnParar.setBounds(480, 420, 123, 40);

        btnMaisCartas.setBackground(new java.awt.Color(255, 255, 255));
        btnMaisCartas.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnMaisCartas.setForeground(new java.awt.Color(255, 255, 255));
        btnMaisCartas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saladejogo/ui/btnMais.png"))); // NOI18N
        btnMaisCartas.setText("MAIS CARTAS");
        btnMaisCartas.setToolTipText("");
        btnMaisCartas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMaisCartas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMaisCartas.setIconTextGap(6);
        btnMaisCartas.setRolloverEnabled(true);
        btnMaisCartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaisCartasActionPerformed(evt);
            }
        });
        add(btnMaisCartas);
        btnMaisCartas.setBounds(280, 420, 123, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saladejogo/ui/logo.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(50, 30, 383, 81);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saladejogo/ui/efeitoDeck.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(200, 290, 510, 60);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Status do Jogo:");
        add(jLabel4);
        jLabel4.setBounds(50, 120, 140, 30);

        lblValorMesa.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblValorMesa.setForeground(new java.awt.Color(255, 0, 0));
        lblValorMesa.setText("$ 15K");
        add(lblValorMesa);
        lblValorMesa.setBounds(180, 152, 45, 16);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Aposta MEGA:");
        add(jLabel3);
        jLabel3.setBounds(50, 150, 140, 20);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("SEUS PONTOS:");
        jLabel6.setToolTipText("");
        add(jLabel6);
        jLabel6.setBounds(340, 370, 170, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saladejogo/ui/copas-10.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel2);
        jLabel2.setBounds(250, 180, 110, 160);

        lblPontos.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblPontos.setText("4");
        add(lblPontos);
        lblPontos.setBounds(520, 370, 170, 30);

        lblFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saladejogo/ui/fundoTestura.png"))); // NOI18N
        lblFundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblFundo);
        lblFundo.setBounds(0, 0, 900, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        Solicitacao parada = new Solicitacao("EOC");
        Solicitacao retorno;
        try
        {
            this.transmissor.writeObject(parada);
            this.transmissor.flush();
            retorno = (Solicitacao) this.receptor.readObject();
            if(retorno.getComando().toUpperCase().equals("SUC"))
            {

            }
        }
        catch (IOException | ClassNotFoundException ex)
        {
            Logger.getLogger(TelaPartida.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPararActionPerformed

    private void btnMaisCartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaisCartasActionPerformed
        Solicitacao pedido = new Solicitacao("COM");
        Solicitacao retorno;
        try
        {
            this.transmissor.writeObject(pedido);
            this.transmissor.flush();
            retorno = (Solicitacao) this.receptor.readObject();
            System.out.println(retorno.toString());
            if(retorno.getComando().toUpperCase().equals("SUC"))
            {

            }
        }
        catch (IOException | ClassNotFoundException ex)
        {
            Logger.getLogger(TelaPartida.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMaisCartasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMaisCartas;
    private javax.swing.JButton btnParar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblPontos;
    private javax.swing.JLabel lblValorMesa;
    // End of variables declaration//GEN-END:variables
}
