/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logindeusuarios.ui;

import java.awt.Color;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.Border;
import logindeusuarios.socket.Conexao;
import logindeusuarios.socket.Solicitacao;

/**
 *
 * @author vntwafi
 */
public class TelaLogin extends javax.swing.JPanel {

    JFrame frameLayout;
    ObjectOutputStream transmissor;
    ObjectInputStream recebido;
    Socket conexao;
    /**
     * Creates new form login
     * @param frameLayout Frame para definir layout da tela
     */
    public TelaLogin(JFrame frameLayout) 
    {
        
        initComponents();
        this.frameLayout = frameLayout;
        this.frameLayout.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.frameLayout.add(this);
        this.frameLayout.pack();
        this.frameLayout.setLocationRelativeTo(null); 
        this.frameLayout.setResizable(false);
        this.frameLayout.setVisible(true);
    }

    TelaLogin() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        lblMensagem = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();

        jLabel3.setText("jLabel3");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("E-mail");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 25, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleName("email");

        jLabel2.setText("Senha");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 55, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleName("senha");

        btnEntrar.setText("Entrar");
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 106, 102, -1));
        btnEntrar.getAccessibleContext().setAccessibleName("btnEntrar");

        btnCadastro.setText("Cadastrar-se");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 106, -1, -1));
        btnCadastro.getAccessibleContext().setAccessibleName("btnCadastro");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 106, -1, -1));
        btnCancelar.getAccessibleContext().setAccessibleName("btnCancelar");

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 300, -1));
        txtEmail.getAccessibleContext().setAccessibleName("txtEmail");

        lblMensagem.setForeground(new java.awt.Color(255, 0, 0));
        add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 84, -1, 10));
        add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 300, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked

        String email = this.txtEmail.getText();
        String senha = String.valueOf(this.txtSenha.getPassword());
        if(!email.isEmpty() && !senha.isEmpty())
        {
            Solicitacao solicitacao = new Solicitacao("LOG", email, senha);
            Solicitacao retorno;
            try
            {
                Conexao.getInstance();
                Conexao.startConnection();
                this.conexao = Conexao.getSocket();
                this.transmissor = Conexao.getOutputStream();
                this.recebido = Conexao.getInputStream();
                
                this.transmissor.writeObject(solicitacao);
                this.transmissor.flush(); //envio imediato
                retorno = (Solicitacao) this.recebido.readObject();
                System.out.println(retorno.toString());
                if(retorno.getComando().toUpperCase().equals("SUC"))
                {
                    this.txtEmail.setText("");
                    this.txtSenha.setText("");
                    this.lblMensagem.setText("Login efetuado com sucesso!");
                    this.lblMensagem.setForeground(Color.green);
                    this.btnEntrar.setEnabled(false);
                    this.btnCadastro.setEnabled(false);
                }
                else
                {
                    this.lblMensagem.setText(retorno.getComplemento1());
                    Conexao.closeConnection();
                }
            }
            catch(Exception e)
            {
                System.out.println(e.getClass());
            }            
        }

    }//GEN-LAST:event_btnEntrarMouseClicked

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        
        this.frameLayout.setVisible(false);
        JFrame frameCadastro = new JFrame("Cadastro");
        TelaCadastro tela = new TelaCadastro(frameCadastro);
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtEmail.setText("");
        txtSenha.setText("");
        if(Conexao.getSocket() != null)
        {
            try 
            {
                Conexao.closeConnection();
                this.lblMensagem.setText("");
                
                if(JOptionPane.showConfirmDialog(null, "Deseja se conectar novamente",
                        "Atenção", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                {
                    Conexao.getInstance();
                    Conexao.startConnection();
                    this.conexao = Conexao.getSocket();
                    this.transmissor = Conexao.getOutputStream();
                    this.recebido = Conexao.getInputStream();
                    this.btnEntrar.setEnabled(true);
                    this.btnCadastro.setEnabled(true);
                }
                else
                {
                    this.btnCadastro.setEnabled(true);
                    System.exit(0);
                }
                
            } 
            catch (IOException ex) 
            {
                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(!validarEmail(this.txtEmail.getText()))
        {
            Border border = BorderFactory.createLineBorder(Color.red, 1);
            this.txtEmail.setBorder(border);

        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained

        this.txtEmail.setBorder(UIManager.getBorder("TextField.border"));
    }//GEN-LAST:event_txtEmailFocusGained

    public static boolean validarEmail(String email)
    {
        boolean isEmailIdValid = false;
        if (email != null && email.length() > 0) {
            String expression = "^[\\w\\.-]+@([\\w\\-]+\\.)+[A-Z]{2,4}$";
            Pattern pattern = Pattern.compile(expression, Pattern.CASE_INSENSITIVE);
            Matcher matcher = pattern.matcher(email);
            if (matcher.matches()) {
                isEmailIdValid = true;
            }
        }
        return isEmailIdValid;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtEmail() {
        return this.txtEmail;
    }

    public JTextField getTxtSenha() {
        return this.txtSenha;
    }


}
